export type TipoCaptura = "MEDIDA_NUMERICA" | "CHECKLIST_BMN" | "FOTO" | "TEXTO" | "TOLERANCIA" | "BOOLEAN";

export interface CampoCaptura {
  key: string;
  label: string;
  tipo: TipoCaptura;
  unidad?: string;
  required?: boolean;
  opciones?: string[];
  grupo?: string;
}

export interface SeccionEvaluacion {
  titulo: string;
  refCampo?: string;
  campos: CampoCaptura[];
}

export interface PlantillaEvaluacion {
  codigo: string;
  nombre: string;
  secciones: SeccionEvaluacion[];
  hallazgosPosibles: string[];
  recomendacionesPosibles: string[];
}

export const PLANTILLAS_EVALUACION: Record<string, PlantillaEvaluacion> = {
  CHVS: {
    codigo: "CHVS",
    nombre: "Cilindro hidráulico vástago simple",
    hallazgosPosibles: [
      "Diámetro interior fuera de tolerancia",
      "Diámetro de salida fuera de tolerancia",
      "Diámetro exterior fuera de tolerancia",
      "Longitud bruñido fuera de tolerancia",
      "Longitud total fuera de especificación",
      "Diámetro ojo fuera de tolerancia",
      "Rayaduras axiales en interior de cilindro",
      "Rayaduras radiales en interior de cilindro",
      "Deformación en diámetro interior",
      "Desgaste en diámetro interior",
      "Desgaste en diámetro de sellado",
      "Golpes en exterior del cilindro",
      "Desgaste en exterior del cilindro",
      "Deformación en exterior de cilindro",
      "Depósitos de soldadura ajenos al diseño original",
      "Tomas defectuosas",
      "Estado de roscas deficiente",
      "Bocina STOP 1 dañada",
      "Bocina STOP 2 dañada",
      "Cáncamo en mal estado",
      "Desgaste excesivo en superficie cromada",
      "Picaduras en superficie cromada",
      "Flexión de barra",
      "Flexión de espiga",
      "Poco espesor de cromo",
      "Desprendimiento de capa de cromo",
      "Excesiva capa de cromo",
      "Daño en superficie roscada de espiga",
      "Fisura en espiga",
      "Fisura en junta",
      "Desgaste en alojamientos de sellos",
      "Corrosión en superficie exterior de tapa",
      "Corrosión en superficie interior de tapa",
      "Fisura o fractura en cuerpo de tapa",
      "Daño en roscas exteriores de tapa",
      "Ovalización en alojamiento de vástago",
      "Desgaste excesivo en émbolo",
      "Desgaste en alojamientos de sellos de émbolo",
      "Corrosión en superficie del émbolo",
      "Golpes o deformación en caras del émbolo",
      "Daño en roscas interiores del émbolo",
      "Fisuras visibles en cuerpo del émbolo",
    ],
    recomendacionesPosibles: [
      "Cambio de cilindro",
      "Reparación mediante cromado",
      "Cambio de vástago",
      "Cambio de tapa",
      "Cambio de émbolo",
      "Cambio de cáncamo",
      "Cambio de cojinete",
      "Cambio de sellos",
      "Limpieza profunda",
      "Prueba de estanqueidad",
      "Inspección mediante NDT",
      "Cambio de elemento de sujeción",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3X", label: "Diámetro Interior A3 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3Y", label: "Diámetro Interior A3 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4X", label: "Diámetro Interior A4 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4Y", label: "Diámetro Interior A4 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongBru", label: "Longitud Bruñido (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilTipoCancamo", label: "Tipo de cáncamo", tipo: "TEXTO", opciones: ["Convencional", "Cóncavo"] },
          { key: "cilDiamOjoX", label: "Diámetro Ojo (F) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilDiamOjoY", label: "Diámetro Ojo (F) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilElemSujecion", label: "Elemento de sujeción", tipo: "TEXTO", opciones: ["Cojinete", "Rótula", "Pin directo"] },
          { key: "cilDintCojX", label: "Diám. Int. elem. sujeción (G) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilDintCojY", label: "Diám. Int. elem. sujeción (G) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilAnchOjo", label: "Ancho de Ojo", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilTomas", label: "Tomas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilBocina1", label: "Bocina STOP 1", tipo: "CHECKLIST_BMN" },
          { key: "cilBocina2", label: "Bocina STOP 2", tipo: "CHECKLIST_BMN" },
          { key: "cilEstadoCancamo", label: "Estado de cáncamo", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Cilindro", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Cilindro", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Cilindro", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "VÁSTAGO",
        refCampo: "refVastago",
        campos: [
          { key: "vasEspX", label: "Diámetro Espiga (A) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasEspY", label: "Diámetro Espiga (A) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasDvasBX", label: "Diámetro Vástago B - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasDvasBY", label: "Diámetro Vástago B - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasDvasCX", label: "Diámetro Vástago C - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasDvasCY", label: "Diámetro Vástago C - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasDvasDX", label: "Diámetro Vástago D - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasDvasDY", label: "Diámetro Vástago D - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Vástago" },
          { key: "vasLongCromo", label: "Longitud Cromo (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasLongTotal", label: "Longitud Total (F)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasLongEspiga", label: "Longitud de Espiga (G)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasTipoCancamo", label: "Tipo de cáncamo", tipo: "TEXTO", opciones: ["Convencional", "Cóncavo"] },
          { key: "vasDextOjoX", label: "Diám. Ext. Ojo (H) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasDextOjoY", label: "Diám. Ext. Ojo (H) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasElemSujecion", label: "Elemento de sujeción", tipo: "TEXTO", opciones: ["Cojinete", "Rótula", "Pin directo"] },
          { key: "vasDintOjoX", label: "Diám. Int. Ojo (I) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasDintOjoY", label: "Diám. Int. Ojo (I) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasDintCojX", label: "Diám. Int. elem. sujeción (J) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasDintCojY", label: "Diám. Int. elem. sujeción (J) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasAnchOjo", label: "Ancho de Ojo", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasFlexB", label: "Flexión B", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasFlexC", label: "Flexión C", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasFlexD", label: "Flexión D", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasCromoB", label: "Espesor Cromo B", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasCromoC", label: "Espesor Cromo C", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasCromoD", label: "Espesor Cromo D", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Flexión y Espesor de Cromo" },
          { key: "vasEstadoCancamo", label: "Estado de cáncamo", tipo: "CHECKLIST_BMN" },
          { key: "vasNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "vasSensor", label: "Sensor", tipo: "CHECKLIST_BMN" },
          { key: "vasComentarios", label: "Comentarios - Vástago y accesorios", tipo: "TEXTO" },
          { key: "vasResultado", label: "Resultado evaluación - Vástago", tipo: "TEXTO" },
          { key: "vasRecomendaciones", label: "Recomendaciones - Vástago", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "TAPA",
        refCampo: "refTapa",
        campos: [
          { key: "tapaDiamExt", label: "Diámetro Exterior (A)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaDiamInt", label: "Diámetro Interior (B)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaDiamSell", label: "Diámetro Sellado (C)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaLongTotal", label: "Longitud Total (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "tapaExtRoscado", label: "Exterior roscado", tipo: "CHECKLIST_BMN" },
          { key: "tapaEstRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "tapaComentarios", label: "Comentarios - Tapa", tipo: "TEXTO" },
          { key: "tapaResultado", label: "Resultado evaluación - Tapa", tipo: "TEXTO" },
          { key: "tapaRecomendaciones", label: "Recomendaciones - Tapa", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "ÉMBOLO",
        refCampo: "refEmbolo",
        campos: [
          { key: "embDiamExt", label: "Diámetro Exterior (A)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "embDiamInt", label: "Diámetro Interior (B)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "embLongTotal", label: "Longitud Total (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "embNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "embIntRoscado", label: "Interior roscado", tipo: "CHECKLIST_BMN" },
          { key: "embEstRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "embComentarios", label: "Comentarios - Émbolo", tipo: "TEXTO" },
          { key: "embResultado", label: "Resultado evaluación - Émbolo", tipo: "TEXTO" },
          { key: "embRecomendaciones", label: "Recomendaciones - Émbolo", tipo: "TEXTO" },
        ],
      },
    ],
  },

  CHP: {
    codigo: "CHP",
    nombre: "Cilindro hidráulico pivotado",
    hallazgosPosibles: [
      "Diámetro interior fuera de tolerancia",
      "Diámetro exterior de pivotantes fuera de tolerancia",
      "Trunnion dañado",
      "Problema en prueba de estanqueidad",
      "Rayaduras axiales en interior de cilindro",
      "Desgaste en exterior del cilindro",
      "Tomas defectuosas",
      "Estado de roscas deficiente",
    ],
    recomendacionesPosibles: [
      "Cambio de cilindro",
      "Reparación mediante cromado",
      "Cambio de trunnion",
      "Prueba de estanqueidad",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3X", label: "Diámetro Interior A3 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3Y", label: "Diámetro Interior A3 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4X", label: "Diámetro Interior A4 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4Y", label: "Diámetro Interior A4 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongBru", label: "Longitud Bruñido (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilTomas", label: "Tomas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilEstadoTrunnion", label: "Estado de trunnion", tipo: "CHECKLIST_BMN" },
          { key: "cilPruebaEstanqueidad", label: "Pasa prueba de estanqueidad", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Cilindro", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Cilindro", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Cilindro", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "PIVOTE",
        refCampo: "refPivote",
        campos: [
          { key: "pivotExtCojX", label: "Diám. Exterior de cojinete - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pivotExtCojY", label: "Diám. Exterior de cojinete - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pivotExtPivotanteX", label: "Diám. Exterior de pivotante - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pivotExtPivotanteY", label: "Diám. Exterior de pivotante - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pivotLongPivotante", label: "Longitud de pivotante", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pivotComentarios", label: "Comentarios - Pivote", tipo: "TEXTO" },
          { key: "pivotResultado", label: "Resultado evaluación - Pivote", tipo: "TEXTO" },
          { key: "pivotRecomendaciones", label: "Recomendaciones - Pivote", tipo: "TEXTO" },
        ],
      },
    ],
  },

  CHPDV: {
    codigo: "CHPDV",
    nombre: "Cilindro hidráulico de pistón de doble vástago",
    hallazgosPosibles: [
      "Diámetro interior fuera de tolerancia",
      "Diámetro exterior fuera de tolerancia",
      "Soporte de sujeción dañado",
      "Problema en prueba de estanqueidad",
      "Rayaduras axiales en interior de cilindro",
      "Tomas defectuosas",
    ],
    recomendacionesPosibles: [
      "Cambio de cilindro",
      "Reparación mediante cromado",
      "Cambio de soporte de sujeción",
      "Prueba de estanqueidad",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3X", label: "Diámetro Interior A3 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3Y", label: "Diámetro Interior A3 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4X", label: "Diámetro Interior A4 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4Y", label: "Diámetro Interior A4 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongBru", label: "Longitud Bruñido (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilTomas", label: "Tomas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilEstadoSoporte", label: "Estado de soporte de sujeción", tipo: "CHECKLIST_BMN" },
          { key: "cilPruebaEstanqueidad", label: "Pasa prueba de estanqueidad", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Cilindro", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Cilindro", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Cilindro", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "PISTÓN",
        refCampo: "refPiston",
        campos: [
          { key: "pistonDiamExt", label: "Diámetro Exterior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pistonDiamInt", label: "Diámetro Interior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pistonLongTotal", label: "Longitud Total", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "pistonNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "pistonComentarios", label: "Comentarios - Pistón", tipo: "TEXTO" },
          { key: "pistonResultado", label: "Resultado evaluación - Pistón", tipo: "TEXTO" },
          { key: "pistonRecomendaciones", label: "Recomendaciones - Pistón", tipo: "TEXTO" },
        ],
      },
    ],
  },

  CHT: {
    codigo: "CHT",
    nombre: "Cilindro hidráulico telescópico",
    hallazgosPosibles: [
      "Diámetro interior de camisa fija fuera de tolerancia",
      "Número de etapas incorrecto",
      "Rayaduras en camisas",
      "Desgaste en camisas móviles",
      "Corrosión en interior",
      "Problemas en estanqueidad",
      "Vástago con flexión",
      "Tapa secundaria dañada",
    ],
    recomendacionesPosibles: [
      "Cambio de cilindro telescópico",
      "Reparación mediante cromado",
      "Cambio de vástago",
      "Cambio de tapa",
      "Cambio de camisas",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (CAMISA FIJA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilTomas", label: "Tomas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Cilindro", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Cilindro", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Cilindro", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "VÁSTAGO",
        refCampo: "refVastago",
        campos: [
          { key: "vasLongCromo", label: "Longitud Cromo", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasLongTotal", label: "Longitud Total", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "vasComentarios", label: "Comentarios - Vástago", tipo: "TEXTO" },
          { key: "vasResultado", label: "Resultado evaluación - Vástago", tipo: "TEXTO" },
          { key: "vasRecomendaciones", label: "Recomendaciones - Vástago", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "TAPAS SECUNDARIAS",
        refCampo: "refTapaSecundaria",
        campos: [
          { key: "tapaSec1Dint", label: "Tapa Secundaria 1 - Diámetro Interior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaSec1Dext", label: "Tapa Secundaria 1 - Diámetro Exterior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaSec2Dint", label: "Tapa Secundaria 2 - Diámetro Interior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaSec2Dext", label: "Tapa Secundaria 2 - Diámetro Exterior", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "tapaSecComentarios", label: "Comentarios - Tapas Secundarias", tipo: "TEXTO" },
          { key: "tapaSecResultado", label: "Resultado evaluación - Tapas Secundarias", tipo: "TEXTO" },
          { key: "tapaSecRecomendaciones", label: "Recomendaciones - Tapas Secundarias", tipo: "TEXTO" },
        ],
      },
    ],
  },

  AE: {
    codigo: "AE",
    nombre: "Acumulador de émbolo",
    hallazgosPosibles: [
      "Diámetro interior fuera de tolerancia",
      "Volumen fuera de especificación",
      "Rayaduras en interior",
      "Corrosión superficial",
      "Tomas defectuosas",
    ],
    recomendacionesPosibles: [
      "Cambio de acumulador",
      "Reparación mediante cromado",
      "Cambio de tomas",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3X", label: "Diámetro Interior A3 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3Y", label: "Diámetro Interior A3 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4X", label: "Diámetro Interior A4 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4Y", label: "Diámetro Interior A4 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongBru", label: "Longitud Bruñido (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilVolumen", label: "Volumen", tipo: "MEDIDA_NUMERICA", unidad: "L" },
          { key: "cilTomas", label: "Tomas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Acumulador", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Acumulador", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Acumulador", tipo: "TEXTO" },
        ],
      },
    ],
  },

  AV: {
    codigo: "AV",
    nombre: "Acumulador de vejiga",
    hallazgosPosibles: [
      "Diámetro de salida 1 fuera de tolerancia",
      "Diámetro de salida 2 fuera de tolerancia",
      "Volumen fuera de especificación",
      "Válvula hidráulica de muelle defectuosa",
      "Vejiga dañada",
    ],
    recomendacionesPosibles: [
      "Cambio de acumulador",
      "Cambio de válvula hidráulica",
      "Cambio de vejiga",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilSalida1X", label: "Diámetro de Salida 1 (A) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalida1Y", label: "Diámetro de Salida 1 (A) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalida2X", label: "Diámetro de Salida 2 (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalida2Y", label: "Diámetro de Salida 2 (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilVolumen", label: "Volumen (E)", tipo: "MEDIDA_NUMERICA", unidad: "L" },
          { key: "cilValvMuelle", label: "Válvula Hid. De Muelle", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Acumulador", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Acumulador", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Acumulador", tipo: "TEXTO" },
        ],
      },
    ],
  },

  RD: {
    codigo: "RD",
    nombre: "Rueda delantera",
    hallazgosPosibles: [
      "Diámetro de alojamiento mayor fuera de tolerancia",
      "Diámetro de asiento de rodamiento fuera de tolerancia",
      "Rodamientos dañados",
      "Corrosión en alojamientos",
      "Daños en alojamientos roscados",
      "Stud dañados",
    ],
    recomendacionesPosibles: [
      "Pulido de asientos de rodamientos",
      "Cambio de rodamientos",
      "Rectificado de alojamientos roscados",
      "Realizar NDT",
      "Pulido de alojamiento cónico",
      "Cambio de Stud",
    ],
    secciones: [
      {
        titulo: "HUB",
        refCampo: "refHub",
        campos: [
          { key: "hubAlojMayorX", label: "Diámetro alojamiento mayor - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "hubAlojMayorY", label: "Diámetro alojamiento mayor - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "hubAlojMenorX", label: "Diámetro alojamiento menor - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "hubAlojMenorY", label: "Diámetro alojamiento menor - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "hubComentarios", label: "Comentarios - HUB", tipo: "TEXTO" },
          { key: "hubResultado", label: "Resultado evaluación - HUB", tipo: "TEXTO" },
          { key: "hubRecomendaciones", label: "Recomendaciones - HUB", tipo: "TEXTO" },
        ],
      },
      {
        titulo: "SPINDLE",
        refCampo: "refSpindle",
        campos: [
          { key: "spindleAsientoMayorX", label: "Diámetro asiento mayor - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "spindleAsientoMayorY", label: "Diámetro asiento mayor - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "spindleAsientoMenorX", label: "Diámetro asiento menor - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "spindleAsientoMenorY", label: "Diámetro asiento menor - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "spindleComentarios", label: "Comentarios - SPINDLE", tipo: "TEXTO" },
          { key: "spindleResultado", label: "Resultado evaluación - SPINDLE", tipo: "TEXTO" },
          { key: "spindleRecomendaciones", label: "Recomendaciones - SPINDLE", tipo: "TEXTO" },
        ],
      },
    ],
  },

  SD: {
    codigo: "SD",
    nombre: "Suspensión delantera",
    hallazgosPosibles: [
      "Diámetro interior fuera de tolerancia",
      "Cartelas dañadas",
      "Tomas defectuosas",
      "Estado de roscas deficiente",
      "Rayaduras en interior",
    ],
    recomendacionesPosibles: [
      "Cambio de cilindro",
      "Reparación mediante cromado",
      "Cambio de cartelas",
      "Cambio de tomas",
      "Inspección mediante NDT",
    ],
    secciones: [
      {
        titulo: "CILINDRO (BOTELLA)",
        refCampo: "refCilindro",
        campos: [
          { key: "cilIntA1X", label: "Diámetro Interior A1 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA1Y", label: "Diámetro Interior A1 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2X", label: "Diámetro Interior A2 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA2Y", label: "Diámetro Interior A2 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3X", label: "Diámetro Interior A3 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA3Y", label: "Diámetro Interior A3 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4X", label: "Diámetro Interior A4 - X", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilIntA4Y", label: "Diámetro Interior A4 - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm", grupo: "Diámetro Interior" },
          { key: "cilSalidaX", label: "Diámetro de Salida (B) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilSalidaY", label: "Diámetro de Salida (B) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtX", label: "Diámetro Exterior (C) - X", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilExtY", label: "Diámetro Exterior (C) - Y", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongBru", label: "Longitud Bruñido (D)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilLongTotal", label: "Longitud Total (E)", tipo: "MEDIDA_NUMERICA", unidad: "mm" },
          { key: "cilEstCartelas", label: "Est. De cartelas", tipo: "CHECKLIST_BMN" },
          { key: "cilRoscada", label: "Est. de sup. Roscada", tipo: "CHECKLIST_BMN" },
          { key: "cilNDT", label: "Pasa a NDT", tipo: "CHECKLIST_BMN" },
          { key: "cilComentarios", label: "Comentarios - Cilindro", tipo: "TEXTO" },
          { key: "cilResultado", label: "Resultado evaluación - Cilindro", tipo: "TEXTO" },
          { key: "cilRecomendaciones", label: "Recomendaciones - Cilindro", tipo: "TEXTO" },
        ],
      },
    ],
  },
};

export function getPlantilla(codigo: string): PlantillaEvaluacion | null {
  return PLANTILLAS_EVALUACION[codigo] ?? null;
}

export function listModelos(): { codigo: string; nombre: string }[] {
  return Object.values(PLANTILLAS_EVALUACION).map((p) => ({ codigo: p.codigo, nombre: p.nombre }));
}
